version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/code

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/code

  beat:
    build: .
    container_name: celery_beat
    command: celery -A app.tasks beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/code

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
